{% set name = "baked-brie" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UNC-CECL/brie/archive/v{{ version }}.tar.gz
  sha256: ff48678ed9540276e216d521eeb44fd50db69fd99959c29143455cc38f34afc2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bmipy
    - numpy
    - pyyaml
    - scipy

test:
  imports:
    - brie
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/UNC-CECL/brie
  summary: 'The Barrier Inlet Environment (BRIE) Model'
  description: |
    This is the python version of the BarrieR Inlet Envrionment (BRIE) model written
    by Jaap Nienhuis and Jorge Lorenzo Trueba.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/UNC-CECL/brie
  dev_url: https://github.com/UNC-CECL/brie

extra:
  recipe-maintainers:
    - mcflugen
